### ISSUE TITLE
[3.9.8] Error installation for blade cli either using JDK 11 from OpenJDK or even from Using sdkman 11.0.21.fx-zulu, cause can't create new liferay workspace

### ISSUE THREAD

**Issue by benyaminl** [liferay/liferay-ide#372]
Hello, I got blade error when installing the IDE, the version that I use is 3.9.8, and I don't know what is the cause, I tried to change java version using FX using sdkman.io, resulting the same. 

![image](https://github.com/liferay/liferay-ide/assets/2817332/910b6d26-7f17-4389-819e-2a518b1f6f04)

Using Zulu and OpenJDK.net 11
```
Problem running post-install step. Installation may not complete correctly
 Error running /home/ben/.sdkman/candidates/java/11.0.21.fx-zulu/bin/java  -jar "/home/ben/LiferayWorkspacewithDevStudio/biz.aQute.jpm.run.jar" install -fl "/home/ben/LiferayWorkspacewithDevStudio/blade.jar": Error
  0. [Source.zerror] Failed java.util.zip.ZipException: Invalid CEN header (invalid extra data field size for tag: 0xbdbf at 27356)
```

It's resulting same if I'm using java 11 openJDK from Ubuntu Repository. I'm at Ubuntu 22.04 LTS with GNOME and GTK3 (if it's matter)

```
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

Using Zulu
```
$ java --version
openjdk 11.0.21 2023-10-17 LTS
OpenJDK Runtime Environment Zulu11.68+17-CA (build 11.0.21+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.68+17-CA (build 11.0.21+9-LTS, mixed mode)
```

Using Ubuntu OpenJDK.net
```
$ java --version
openjdk 11.0.20.1 2023-08-24
OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```

This error lead to can't create a new Liferay workspace, that cause me can't create a new module. 
![image](https://github.com/liferay/liferay-ide/assets/2817332/96d1c869-d671-45ae-9cd7-bf801aaa2196)
```
com.liferay.ide.project.core.modules.BladeCLIException: 
	at com.liferay.ide.project.core.modules.BladeCLI._execute(BladeCLI.java:216)
	at com.liferay.ide.project.core.modules.BladeCLI.executeWithLatestBlade(BladeCLI.java:59)
	at com.liferay.ide.maven.core.LiferayMavenWorkspaceProjectProvider.createNewProject(LiferayMavenWorkspaceProjectProvider.java:76)
	at com.liferay.ide.maven.core.LiferayMavenWorkspaceProjectProvider.createNewProject(LiferayMavenWorkspaceProjectProvider.java:1)
	at com.liferay.ide.project.core.workspace.NewLiferayWorkspaceOpMethods.execute(NewLiferayWorkspaceOpMethods.java:55)
	at com.liferay.ide.project.core.workspace.NewLiferayWorkspaceOp$Impl.execute(Unknown Source)
	at org.eclipse.sapphire.ui.forms.swt.SapphireWizard.performFinish(SapphireWizard.java:398)
	at org.eclipse.sapphire.ui.forms.swt.SapphireWizard$3.run(SapphireWizard.java:362)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

Failed to init product version list.

```
com.liferay.ide.project.core.modules.BladeCLIException: 
	at com.liferay.ide.project.core.modules.BladeCLI._execute(BladeCLI.java:216)
	at com.liferay.ide.project.core.modules.BladeCLI.getWorkspaceProducts(BladeCLI.java:146)
	at com.liferay.ide.project.core.workspace.ProductVersionPossibleValuesService$1.run(ProductVersionPossibleValuesService.java:83)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I'm just suspecting that the blade.jar header building is wrong, resulting this error, but as I'm new into liferay, I can't debug much. I hope there are some pointer regarding fixing this problem. Thank you

**Comment by benyaminl** [comment]
Seems there are ticket for it.. haiyah.. 
https://liferay.atlassian.net/jira/software/c/projects/IDE/issues/IDE-5117

I will close this..

**Comment by rithvikhashclude** [comment]
Is this issue resolved? i am getting the same error? i installed 3.98 in my windows system, how do i fix this issue?

**Comment by benyaminl** [comment]
@rithvikhashclude , I use sdkman in the end to use multiple JDK on my machine. I think based on the ticket, it should be fixed already.
